import { Product } from './types/Product'

export const sampleProducts: Product[] = [
  {
    name: 'Dress Russian Style 1',
    slug: 'dress-rus-style-1',
    image: '../images/russian-style-1.jpeg',
    category: 'Dresses',
    brand: 'Poupée russe',
    price: 190,
    countInStock: 2,
    description: 'dress for special occasions',
    rating: 9.3,
    numReviews: 10,
  },
  {
    name: 'Dress Russian Style 2',
    slug: 'dress-rus-style-2',
    image: '../images/russian-style-2.jpg',
    category: 'Dresses',
    brand: 'Poupée russe',
    price: 180,
    countInStock: 3,
    description: 'dress for special occasions',
    rating: 9.9,
    numReviews: 10,
  },
  {
    name: 'Dress Russian Style 3',
    slug: 'dress-rus-style-3',
    image: '../images/russian-style-3.jpg',
    category: 'Dresses',
    brand: 'Poupée russe',
    price: 110,
    countInStock: 7,
    description: 'dress for special occasions',
    rating: 8.9,
    numReviews: 5,
  },
  {
    name: 'Dress Russian Style 4',
    slug: 'dress-rus-style-4',
    image: '../images/russian-style-4.jpg',
    category: 'Dresses',
    brand: 'Poupée russe',
    price: 130,
    countInStock: 4,
    description: 'dress for special occasions',
    rating: 9.3,
    numReviews: 4,
  },
]
